android_devices:
  - id: "pixel-9xl"
    name: "Google Pixel 9XL"
    ip_address: "192.168.1.101" # TODO: Configure with your device's local IP
    ssh_user: "termux"
    ssh_key_name: "termux_ssh_key" # The name of the secret in Vault

  - id: "samsung-s9-tablet"
    name: "Samsung S9+ Tablet"
    ip_address: "192.168.1.102" # TODO: Configure with your device's local IP
    ssh_user: "termux"
    ssh_key_name: "termux_ssh_key" # The name of the secret in Vault
