apiVersion: v1
kind: ServiceAccount
metadata:
  name: wilsons-raider
  namespace: wilsons-raider
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: wilsons-raider
  namespace: wilsons-raider
rules:
  - apiGroups: [""]
    resources: ["pods", "services", "configmaps"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch", "create", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: wilsons-raider
  namespace: wilsons-raider
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: wilsons-raider
subjects:
  - kind: ServiceAccount
    name: wilsons-raider
    namespace: wilsons-raider
